name: Publish telegram-client to GitHub Packages
on:
    push:
      tags:
        - "v*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                node-version: 23.5.0
                token: ${{ secrets.CHAINHACKERS_NPM_TOKEN }}

            - run: npm --prefix `pwd` ci
              working-directory: ./packages/client-telegram

            - run: npm run build
              working-directory: ./packages/client-telegram

            - run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.CHAINHACKERS_NPM_TOKEN }}
