name: Publish telegram-client to GitHub Packages
on:
    push:
      tags:
        - "v*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v
              with:
                fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                node-version: 22
                registry-url: 'https://npm.pkg.github.com'

            - uses: pnpm/action-setup@v3
              with:
                version: 9.4.0

            - name: Install Protobuf Compiler
              run: sudo apt-get install -y protobuf-compiler

            - run: pnpm install
              working-directory: ./packages/client-telegram

            - run: pnpm run build
              working-directory: ./packages/client-telegram

            - run: npm publish
              working-directory: ./packages/client-telegram
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
